name: Curriculum Solution Branch Splitter

on:
  push:
    branches: curriculum
    paths: index.ipynb

jobs:
  Test_remote_action:
    uses: learn-co-curriculum/dsc-github-actions-files/blob/autotest/.github/workflows/black_format.yml@v0.0.3a
    secrets: inherit
   
